spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/olx_db
    username: postgres
    password: user
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
  data:
    web:
      pageable:
        one-indexed-parameters: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 50MB
images-storage-path: C:/Users/Игорь/Desktop/java/MyOLX/src/main/resources/static/images